services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: filesdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
  
  api:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./app:/app
      - ./requirements.txt:/requirements.txt

    ports:
      - "8000:8000"
    depends_on:
      - minio
      - postgres
    command: >
      bash -c "
      pip install -r /requirements.txt &&
      uvicorn main:app --host 0.0.0.0 --port 8000
      "